server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092